config/routes.rb
Rails.application.routes.draw do
  #root will be the list of support tickets
  root "requests#index"

  #add the routes for support requests (requests)
  resources :requests

  #add a route for the search method
  get "/search" => "requests#search"

end

app/models/request.rb
class Request < ActiveRecord::Base

	#--VALIDATIONS-------------------------------------
	#validate for presence of name and email
	validates :name, :email, presence: true

	#--------------------------------------------------


	#--CALLBACKS---------------------------------------
	#on initialization, set the default status to be incomplete
	#see class method below
	after_initialize :set_defaults

	#--------------------------------------------------


	#--CLASS METHODS--------------------------------------
	#search method to search by email, name and message
	#this will find emails, names, or messages with a given string of characters
	def self.search_query(input)
		#create a query to search for a specific term, input by the user
		where("name LIKE ? OR email LIKE ? or message LIKE ?", "%#{input}%", "%#{input}%", "%#{input}%")
	end

	#this method will sort by incomplete tasks first
	def self.status_sort
		#show the incomplete tasks on top
		#should sort alphabetically for the status column, so incomplete
		#tasks show first
		order(status: :DESC)
	end

	#this will add pagination and show 5 results per page
	#used for both index page and search results page
	def self.pag(page, per_page = 5)
			offset(page * per_page).first(per_page)
	end


	#--PRIVATE CLASS METHODS ------------------------------------

	private

	#this method will set the default value of status to incomplete
	def set_defaults
		self.status ||= "incomplete"
	end

	#-----------------------------------------------------

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController

	#before action will utilize this method in the specified actions
	before_action :my_request, only: [:show, :edit, :destroy, :update, :update_status]

	#display the index page for this controller
	#show a list of all of the support requests, sorted by incomplete
	#first, with pagination
	def index	
		#----------FOR PAGINATION -----------------------------------
		#use this variable to calculate the total number of pages 
		#needed to display all of the posts
		@all = Request.all.count / 10

		#the will be passed into the pag method.  Need to convert the
		#value from params: to an interger.  Default should be zero.
		@page = params[:page].to_i || 0
		
		#pass the @page variable into pag method, and show the index
		#page again
		@requests = Request.pag(@page, 5)
		render :index
		#-----------------------------------------------------------
	end

	#view to create a new request
	def new
		#instantiate a variable for the new request
		@request = Request.new
	end


	#action to add the new request to the database using post
	def create
		#create the new request
		@request = Request.new(request_params)

		#if the request saves, go to that request show page.  If not, return
		#to this create page displaying the error messages
		if @request.save 
			redirect_to request_path(@request), noticed: "support ticket created successfully"
		else
			render :new
		end
	end


	#action to show the specific request
	def show
		#before_action will grab the ticket by its id
	end

	#action to edit the ticket (just the view)
	def edit
		#before_Action will grab the ticket by its id
	end

	#action to update the ticket (patch)
	def update

		@complete = params[:status] == "complete"
		#before_action will grab the ticket by its id
		#need to add in the params to update the request using strong params
		#if it updates, go to the show page.  If not, stay on same page and
		#display error messages
		if @request.update(request_params)
			#show a message saying it's been updated
			redirect_to requests_path, notice: "record updated successfully"
		else
			render :edit
		end
	end

	#action to delete a support ticket (delete)
	def destroy
		#before_action will grab the ticket by its id
		@request.destroy
		#go back to the request listing page, and show a notice that it has
		#been successfully deleted
		redirect_to requests_path, notice: "Record Deleted Successfully"
	end


	#search action, as defined in the model
	#use pagination as well
	def search
		#use this variable to calculate the total number of pages 
		#needed to display all of the requests
		@all = Request.search_query(params[:input]).count / 10

		#the will be passed into the pag method.  Need to convert the
		#value from params: to an interger.  Default should be zero.
		@page = params[:page].to_i || 0

		#store the results in an array, results, and render the search
		#results on a new page, search.html.erb, adding the pagination method
		@result = Request.search_query(params[:input]).pag(@page, 5)
		render :search
	end


	#private methods only to be used for this class
	private

	#strong params
	def request_params
		request_params = params.require(:request).permit(:name, :email, :department, 
																	:message, :status)
	end


	#getting a request by its specific id
	def my_request
		@request = Request.find(params[:id])
	end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Supporter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<%# --------HEADER LINKS ----------------------------%>
	<%# links to main pages on the site %>
	<%= link_to "All Requests", requests_path %> |  
	<%= link_to "Create New Request", new_request_path %>
	<br>
	<br>
	<hr>

	<%# -------FLASH MESSAGES ----------------------------- %>
	<%# space to display the flash messages %>
	<%= flash[:notice] || flash[:alert] %>
	<br>
	<hr>

	<%# --- SEARCH BAR -------------------------------------%>
	<%# search for a specific record %>
	<%= form_tag("/search", method: "get") do %>
  		<%= label_tag(:input, "Search for:") %>
  		<%= text_field_tag(:input) %>
  		<%= submit_tag("Search") %>
	<% end %>


<%= yield %>

</body>
</html>

app/views/requests/_form.html.erb
<%# this form will check and display any errors when filling out the form%>
<% if @request.errors.any? %>
	<% @request.errors.full_messages.each do |message|%>
		<%= message %>
	<% end %>
<% end %>


<%#form to create a new request %>
<%= form_for @request do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<br>
	<%= f.label :email %>
	<%= f.text_field :email %>
	<br>
	<%= f.label :department %>
	<%= f.radio_button(:department, "sales") %>
	<%= f.label(:department, "Sales") %>
	<%= f.radio_button(:department, "marketing") %>
	<%= f.label(:department, "Marketing") %>
	<%= f.radio_button(:department, "technical") %>
	<%= f.label(:department, "Technical") %>
	<br>
	<%= f.label :message %>
	<%= f.text_area :message %>
	<br>
	<%= f.submit %>

<% end %>

app/views/requests/edit.html.erb
<h1>Edit This Support Request</h1>

<%# render the partial _form %>
<%= render "form" %>

app/views/requests/index.html.erb
<h1>View All Support Requests</h1>

<%# --- DISPLAY THE RESULTS IN A TABLE ----------------------------- %>
<table>
	<tr>
		<th>Name</th>
		<th>Email</th>
		<th>Department</th>
		<th>Description</th>
		<th>Status (I / C)</th>
		<th>Actions</th>
	</tr>
	<% @requests.each do |r| %>
	<tr>
		<td><%= r.name %></td>
		<td><%= mail_to r.email %></td>
		<td><%= r.department %></td>
		<td><%= r.message %></td>
		<td>
				<%# ---- BUTTON TO CHANGE STATUS OF PROJECTS --------- %>

				<% if r.status == "incomplete" %>
          <%= link_to "Mark Complete", request_path(r, request: {status: "complete"}), method: :patch %>
        <% else %>
          <%= link_to "Mark Incomplete", request_path(r, request: {status: "incomplete"}), method: :patch %>
        <% end %>


				<%# ----------------------------------------------------- %>
		<td>

			<%# --- ADD LINKS TO EDIT, VIEW, AND DELETE RECORDS ----------%>
			<%= link_to "View", request_path(r) %>
			<%= link_to "Edit", edit_request_path(r) %>
			<%= button_to "Delete", request_path(r), method: :delete, data: {confirm: "Are you sure you want to delete this support request?"} %>
		</td>
	</tr>
<% end %>
</table>

<%#-----------------------------------------------------------------------%>

<%# --- FOR PAGINATION.  USED MY OWN METHOD..NO GEM -----------------------%>
<%# for pagination.  Only show these links under the following conditions %>
<% if @page > 0 %>
	<%= link_to "Previous 5 results", requests_path(page: @page - 1) %>
<% end %>

<%# only show this link for the following condition %>
<% if @page < @all %>
	<%= link_to "Next 5 Results", requests_path(page: @page + 1) %>
<% end %>

<%# ------------------------------------------------------------------------%>




	







	

app/views/requests/new.html.erb
<h1> Create A New Support Ticket </h1>

<%= render "form" %>

app/views/requests/search.html.erb
<h1>Here are the tickets matching your search</h1
<%# ---- TABLE TO RENDER THE SUPPORT TICKET ------- %>
<table>
	<tr>
		<th>Name</th>
		<th>Email</th>
		<th>Department</th>
		<th>Description</th>
		<th>Status (I / C)</th>
		<th>Actions</th>
	</tr>
	<% @result.each do |r| %>
	<tr>
		<td><%= r.name %></td>
		<td><%= r.email %></td>
		<td><%= r.department %></td>
		<td><%= r.message %></td>
		<td><%= r.status %></td>
		<td>
			<%= link_to "View", request_path(r) %>
			<%= link_to "Edit", edit_request_path(r) %>
			<%= button_to "Delete", request_path(r), method: :delete, data: {confirm: "Are you sure you want to delete this support request?"} %>
		</td>
	</tr>
<% end %>
</table>

<%# ---- DISPLAY THE PAGNATION OPTIONS ------------------- %>
<%# display the current page of results %>
<p>Page <%= @page + 1 %></p>

<%# only display this link under these conditions %>
<% if @page > 0 %>
<%= link_to "Previous 5 results", search_path(page: @page - 1) %>
<% end %>


<%# only display this link under these conditions %>
<% if @page < @all %>
<%= link_to "Next 5 Results", search_path(page: @page + 1) %>
<% end %>

app/views/requests/show.html.erb
<h1>View This Support Ticket</h1>

<h2>Name:</h2>
<%= @request.name %>
<br>
<br>
<h2>Email</h2>
<%= mail_to @request.email %>
<br>
<br>
<h2>Department</h2>
<%= @request.department %>
<br>
<br>
<h2>Message</h2>
<%= @request.message %>
<br>
<br>
<h2>Status</h2>
<%= @request.status %>
<br>
<br>

<%#link to edit the ticket %>
<%= link_to "Edit", edit_request_path(@request) %>
<br>

<%# link to delete the ticket %>
<%# add a message pop-up to confirm if they want to delete it or not %>
<%= button_to "Delete", request_path(@request), method: :delete, data: {confirm: "Are you sure you want to delete this support request?"} %>
<br>

<%# link to update the status to Complete %>
<%= link_to "Mark As Complete", request_path(request:{status: "complete"}), method: :put %>  |
<br>
<%# link to update the status to incomplete %>
<%= link_to "Mark As Incomplete", request_path(request:{status: "incomplete"}), method: :put %>